name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      - name: Update Conda environment with "environment.yml"
        uses: matthewrmshin/conda-action@v1
        with:
          args: conda env update -f ./environment.yml
      - name: Run tests
        run: coverage run tests/TestNeuroHealthApp.py
      - name: Tests report
        run: coverage report