name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  unittests_and_coverage:
    runs-on: ubuntu-latest
    steps:
      # Чекаутим код
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: nhc_dev
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: true
      - run: |
          conda info
          conda list
        
      # - uses: s-weigand/setup-conda@v1
      #   with:
      #     update-conda: true
      #     conda-channels: anaconda, conda-forge
      #     activate-conda: false
      
      # - name: Conda info
      #   run: conda info | grep -i 'base environment'

      # - name: Create conda environment with "environment.yml"
      #   run: conda env create --name nhc_dev --file environment.yml
      #   run: conda env update --file environment.yml --name base
      
      # - name: Conda activation with conda.sh
      #   run: source /usr/share/miniconda/etc/profile.d/conda.sh
      
      # - name: Conda init
      #   shell: bash -l {0}
      #   run: conda init
      
      # - name: Activate conda environment
      #   shell: bash -l {0}
      #   run: conda activate base
      
      - name: Run unit tests
        run: coverage run tests/TestNeuroHealthApp.py
      
      - name: Show tests report
        run: coverage report